---
output:
  pdf_document: default
---
\newpage
\addtocounter{section}{2}

# CHAPTER 3: RESULTS

## 3.1 Introduction 
In this chapter, we show the results of the analysis of......

## 3.2 Exploratory Data Analysis

## 3.2.1 
Result Exploratory Data Analysis 1

### 3.2.2 
Result Exploratory Data Analysis 2


## 3.3 Bivariate Analysis
The code for the table can be generated from https://www.tablesgenerator.com/  and put between  begin {table} and end {table}
<!-- include a table in a landscape page  -->

\blandscape
\begin{table}
\centering
\captionsetup{font=scriptsize}
\resizebox{\textwidth}{!}{%
\normalsize
\renewcommand{\arraystretch}{1} 


\begin{tabular}{lllllllllll}
\toprule
Variables & \multicolumn{3}{c}{Overall} & \multicolumn{3}{c}{Data1} & \multicolumn{3}{c}{Data2}  &  P-value \\
& N (total ) &    Mean &    SD (O,B,W) &N (total ) & Mean    & SD (O,B,W) & N (total )    & Mean  &    SD (O,B,W)  &    \\
\midrule
Age & 3114 (7820) & 35.95 & 32.56 & 3114 (7621) & 35.71 & 32.35 & 199 ( 199) & 45.16 & 38.69 & 0.0001 \\
 &  &  & 28.53 &  &  & 28.48 &  &  & 38.69 &  \\
 &  &  & 14.73 &  &  & 14.46 &  &  & N/A &  \\
 \midrule
 Days & 3113 (7780) & 5.18 & 6.61 & 3113 (7591) & 5.15 & 6.53 & 189 ( 189) & 6.51 & 9.16 & 0.0067 \\
 &  &  & 4.95 &  &  & 5.04 &  &  & 9.16 &  \\
 &  &  & 4.45 &  &  & 4.34 &  &  & N/A &  \\
 \midrule
Number of  & 3114 (7820) & 3.49 & 2.56 & 3114 (7621) & 3.50 & 2.58 & 199 ( 199) & 2.96 & 1.75 & 0.0036 \\
 &  &  & 1.59 &  &  & 1.59 &  &  & 1.75 &  \\
 &  &  & N/A &  &  & N/A &  &  & N/A &  \\
 \midrule
Total  & 3114 (7820) & 3.22 & 2.27 & 3114 (7621) & 3.23 & 2.29 & 199 ( 199) & 2.67 & 1.37 & 0.0007 \\
 &  &  & 1.37 &  &  & 1.37 &  &  & 1.37 &  \\
 &  &  & N/A &  &  & N/A &  &  & N/A &  \\
 \midrule
Weight  & 3109 (7736) & 10.96 & 5.17 & 3108 (7541) & 10.97 & 5.13 & 195 ( 195) & 10.53 & 6.38 & 0.2597 \\
 &  &  & 4.69 &  &  & 4.68 &  &  & 6.38 &  \\
 &  &  & 2.16 &  &  & 2.13 &  &  & N/A &  \\
 \midrule
Height  & 3092 (7526) & 85.17 & 19.06 & 3088 (7350) & 85.12 & 18.98 & 176 ( 176) & 87.05 & 22.45 & 0.1939 \\
 &  &  & 17.09 &  &  & 17.14 &  &  & 22.45 &  \\
 &  &  & 8.53 &  &  & 8.40 &  &  & N/A &  \\
\midrule
Water (mm) & 3070 (7426) & 31.92 & 44.30 & 3068 (7236) & 31.78 & 44.02 & 190 ( 190) & 37.27 & 53.79 & 0.1002 \\
 &  &  & 32.42 &  &  & 32.78 &  &  & 53.79 &  \\
 &  &  & 32.84 &  &  & 32.30 &  &  & N/A & \\
\bottomrule
\end{tabular}%
}


\caption{Characteristics of the study population for the continous variables a bivariate analysis by mortality; SD(O,B,W)  is the overall, within and between Standard Deviation}
\label{tab:table1}
\end{table} 
\elandscape



## 3.4 Inferential 1  Model Fit and Diagnostics
### 3.4.1 Model fit results
orem Ipsum is simply dummy text of the printing and typesetting industry. 
### 3.4.2 Model fit diagnostics
orem Ipsum is simply dummy text of the printing and typesetting industry. 

## 3.5 Inferential 2  Model Fit and Diagnostics
### 3.5.1 Model fit results
orem Ipsum is simply dummy text of the printing and typesetting industry. 

### 3.5.2 Model fit diagnostics
orem Ipsum is simply dummy text of the printing and typesetting industry. 